manifest = "d5fde10aab37022393de6ba9a2b6dd3371edd2ff6278c1081f0c44b5e190d999"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
target = "//:iterator"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-range"
target = "//:range"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.39.0" ]
revision = "eb4ad60cdc89bc3de6f020085165a9527a145034"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.39.0" ]
revision = "8d2669c973073bf1be4238a318c2784dd0999630"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.39.0" ]
revision = "478a355bb52452bc27d16e2b68cf6677e09f3c96"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.39.0" ]
revision = "95158e066ba147c3d3c392f20ce8e64b86cd4f33"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.39.0" ]
revision = "2ae6217c88649cc02ab2a5f35b493724c7d9c597"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.39.0" ]
revision = "87e9eb41400a0eb04cfb81af1be42d1179b09b8b"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.39.0" ]
revision = "4eec76990f5dc380cd7e6e8106796ce91c5568f5"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.39.0" ]
revision = "aa9b48173569be31a060373000a54287e15422b8"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.39.0" ]
revision = "8afc104545d5cc4b9c164af7d5a274cfa9b87eb5"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.39.0" ]
revision = "ac39e74ef9ca023c9780279df0bf89ca68cc64e9"
